/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SearchRouteImport } from './routes/search'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ArtistUserIdRouteImport } from './routes/artist.$userId'
import { Route as PlaylistPlaylistIdRouteImport } from './routes/playlist.$playlistId'
import { Route as TrackTrackIdRouteImport } from './routes/track.$trackId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistUserIdRoute = ArtistUserIdRouteImport.update({
  id: '/artist/$userId',
  path: '/artist/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistPlaylistIdRoute = PlaylistPlaylistIdRouteImport.update({
  id: '/playlist/$playlistId',
  path: '/playlist/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTrackIdRoute = TrackTrackIdRouteImport.update({
  id: '/track/$trackId',
  path: '/track/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/artist/$userId': typeof ArtistUserIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/track/$trackId': typeof TrackTrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/artist/$userId': typeof ArtistUserIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/track/$trackId': typeof TrackTrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/artist/$userId': typeof ArtistUserIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/track/$trackId': typeof TrackTrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/search'
    | '/upload'
    | '/artist/$userId'
    | '/playlist/$playlistId'
    | '/track/$trackId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/search'
    | '/upload'
    | '/artist/$userId'
    | '/playlist/$playlistId'
    | '/track/$trackId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/search'
    | '/upload'
    | '/artist/$userId'
    | '/playlist/$playlistId'
    | '/track/$trackId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  SearchRoute: typeof SearchRoute
  UploadRoute: typeof UploadRoute
  ArtistUserIdRoute: typeof ArtistUserIdRoute
  PlaylistPlaylistIdRoute: typeof PlaylistPlaylistIdRoute
  TrackTrackIdRoute: typeof TrackTrackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$userId': {
      id: '/artist/$userId'
      path: '/artist/$userId'
      fullPath: '/artist/$userId'
      preLoaderRoute: typeof ArtistUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$playlistId': {
      id: '/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof PlaylistPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$trackId': {
      id: '/track/$trackId'
      path: '/track/$trackId'
      fullPath: '/track/$trackId'
      preLoaderRoute: typeof TrackTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  SearchRoute: SearchRoute,
  UploadRoute: UploadRoute,
  ArtistUserIdRoute: ArtistUserIdRoute,
  PlaylistPlaylistIdRoute: PlaylistPlaylistIdRoute,
  TrackTrackIdRoute: TrackTrackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
